---
# Use container-based infrastructure
sudo: false

language: python
python:
  - "3.6"
install:
  - pip install coveralls
script:
  - coverage run --source=src setup.py test
after_success:
  - coveralls

